./nvim              $XDG_CONFIG_HOME/nvim
./fish              $XDG_CONFIG_HOME/fish
./terminal/ghostty  $XDG_CONFIG_HOME/ghostty
./tools/rmpc        $XDG_CONFIG_HOME/rmpc
./tools/yazi        $XDG_CONFIG_HOME/yazi
./tools/zellij      $XDG_CONFIG_HOME/zellij

./rime              $HOME/Library/Rime
./tools/mpd         $HOME/.mpd
./wm/hammerspoon    $HOME/.hammerspoon
